const mongoose = require('mongoose');

const SubtitleSchema = new mongoose.Schema({
  video: { type: mongoose.Schema.Types.ObjectId, ref: 'Video', required: true },
  language: { type: String, required: true },
  label: { type: String },
  isAutoGenerated: { type: Boolean, default: false },
  isDubbed: { type: Boolean, default: false },
  dubAudioUrl: { type: String },
  dubVoiceId: { type: String },
  segments: [{
    id: Number,
    start: Number,
    end: Number,
    text: String,
    translatedText: String,
  }],
  status: {
    type: String,
    enum: ['pending', 'processing', 'completed', 'failed'],
    default: 'pending',
  },
  progress: { type: Number, default: 0 },
  createdAt: { type: Date, default: Date.now },
});

SubtitleSchema.index({ video: 1, language: 1 }, { unique: true });

module.exports = mongoose.model('Subtitle', SubtitleSchema);
