const mongoose = require('mongoose');

const VideoSchema = new mongoose.Schema(
  {
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
    },
    title: {
      type: String,
      required: [true, 'Title is required'],
      trim: true,
      maxlength: [100, 'Title cannot exceed 100 characters'],
    },
    description: {
      type: String,
      maxlength: [5000, 'Description cannot exceed 5000 characters'],
      default: '',
    },
    url: {
      type: String,
      required: true,
    },
    thumbnail: {
      type: String,
      required: true,
    },
    thumbnailGenerated: {
      type: Boolean,
      default: false,
    },
    duration: {
      type: Number,
      default: 0,
    },
    tags: [
      {
        type: String,
        trim: true,
      },
    ],
    category: {
      type: String,
      enum: [
        'Music',
        'Gaming',
        'Education',
        'Entertainment',
        'Sports',
        'News',
        'Technology',
        'Science',
        'Travel',
        'Food',
        'Fashion',
        'Comedy',
        'Documentary',
        'Vlog',
        'Tutorial',
        'Other',
      ],
      default: 'Other',
    },
    views: {
      type: Number,
      default: 0,
    },
    likes: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
      },
    ],
    dislikes: [
      {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
      },
    ],
    isPublic: {
      type: Boolean,
      default: true,
    },
    isProcessed: {
      type: Boolean,
      default: false,
    },
    processingProgress: {
      type: Number,
      default: 0,
    },
    status: {
      type: String,
      enum: ['uploading', 'processing', 'ready', 'failed'],
      default: 'uploading',
    },
    resolution: {
      type: String,
      enum: ['144p', '240p', '360p', '480p', '720p', '1080p', '4K'],
      default: '720p',
    },
    format: {
      type: String,
      default: 'mp4',
    },
    fileSize: {
      type: Number,
      default: 0,
    },
    language: {
      type: String,
      default: 'en',
    },
    allowComments: {
      type: Boolean,
      default: true,
    },
    isDownloadable: {
      type: Boolean,
      default: true,
    },
    aiTitle: { type: String },
    aiTags: [String],
    aiThumbnail: { type: String },
    shares: {
      type: Number,
      default: 0,
    },
    videoResolutions: [String],
    captions: [
      {
        language: { type: String },
        url: { type: String },
        autoGenerated: { type: Boolean, default: false },
      },
    ],
    moderated: {
      type: Boolean,
      default: false,
    },
    moderationPassed: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
  }
);

VideoSchema.index({ title: 'text', description: 'text', tags: 'text' });
VideoSchema.index({ category: 1, createdAt: -1 });
VideoSchema.index({ views: -1 });
VideoSchema.index({ user: 1, createdAt: -1 });

module.exports = mongoose.model('Video', VideoSchema);
