const PDFDocument = require('pdfkit');

function generateSummaryPDF(summaryData, channelName, videoTitle) {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers = [];
      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);

      const font = 'Helvetica';
      const bold = 'Helvetica-Bold';

      doc.font(bold).fontSize(22).text('Video Summary', { align: 'center' });
      doc.moveDown(0.3);
      doc.font(font).fontSize(12).fillColor('#666').text(`Generated by FunTube AI`, { align: 'center' });
      doc.moveDown(0.5);

      doc.fontSize(14).fillColor('#000').font(bold).text(videoTitle || 'Untitled');
      doc.font(font).fontSize(11).fillColor('#666').text(`Channel: ${channelName || 'Unknown'}`);
      doc.moveDown(0.3);
      doc.font(font).fontSize(10).fillColor('#999').text(`Generated: ${new Date().toLocaleDateString()}`);
      doc.moveDown(1);

      for (const level of summaryData.levels || []) {
        if (doc.y > 700) doc.addPage();
        doc.addMeta('header', '');
        doc.font(bold).fontSize(16).fillColor('#a21caf').text(`${level.level.toUpperCase()} LEVEL`);
        doc.moveDown(0.5);

        if (level.shortSummary) {
          doc.font(bold).fontSize(12).fillColor('#000').text('Short Summary');
          doc.font(font).fontSize(10).fillColor('#333').text(level.shortSummary, { indent: 10 });
          doc.moveDown(0.5);
        }

        if (level.detailedSummary) {
          if (doc.y > 680) doc.addPage();
          doc.font(bold).fontSize(12).fillColor('#000').text('Detailed Summary');
          doc.font(font).fontSize(10).fillColor('#333').text(level.detailedSummary, { indent: 10 });
          doc.moveDown(0.5);
        }

        if (level.bulletPoints?.length) {
          if (doc.y > 680) doc.addPage();
          doc.font(bold).fontSize(12).fillColor('#000').text('Key Points');
          for (const point of level.bulletPoints) {
            doc.font(font).fontSize(10).fillColor('#333').text(`  • ${point}`, { indent: 10 });
          }
          doc.moveDown(0.5);
        }

        if (level.timestamps?.length) {
          if (doc.y > 680) doc.addPage();
          doc.font(bold).fontSize(12).fillColor('#000').text('Timestamps');
          for (const ts of level.timestamps) {
            const mins = Math.floor(ts.time / 60);
            const secs = ts.time % 60;
            const stamp = `${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}`;
            doc.font(bold).fontSize(10).fillColor('#a21caf').text(`  ${stamp} - ${ts.label}`, { indent: 10, continued: true });
            doc.font(font).fillColor('#666').text(` ${ts.description || ''}`);
          }
          doc.moveDown(0.5);
        }

        if (level.faqs?.length) {
          if (doc.y > 680) doc.addPage();
          doc.font(bold).fontSize(12).fillColor('#000').text('FAQs');
          for (const faq of level.faqs) {
            doc.font(bold).fontSize(10).fillColor('#000').text(`  Q: ${faq.question}`, { indent: 10 });
            doc.font(font).fillColor('#333').text(`  A: ${faq.answer}`, { indent: 20 });
            doc.moveDown(0.3);
          }
          doc.moveDown(0.3);
        }

        if (level.revisionNotes?.length) {
          if (doc.y > 680) doc.addPage();
          doc.font(bold).fontSize(12).fillColor('#000').text('Revision Notes');
          for (const note of level.revisionNotes) {
            doc.font(font).fontSize(10).fillColor('#333').text(`  • ${note}`, { indent: 10 });
          }
          doc.moveDown(0.5);
        }

        doc.moveDown(1);
      }

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

module.exports = { generateSummaryPDF };
